package com.goumen.xiwan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BookInfo {
    @Override
    public String toString() {
        return "BookInfo{" +
                "id=" + id +
                ", bookId=" + bookId +
                ", bookName='" + bookName + '\'' +
                ", author='" + author + '\'' +
                ", press='" + press + '\'' +
                ", number=" + number +
                ", price=" + price +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.book_name
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.author
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.press
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.number
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.price
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.id
     *
     * @return the value of book_info.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.id
     *
     * @param id the value for book_info.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.book_id
     *
     * @return the value of book_info.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.book_id
     *
     * @param bookId the value for book_info.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.book_name
     *
     * @return the value of book_info.book_name
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.book_name
     *
     * @param bookName the value for book_info.book_name
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.author
     *
     * @return the value of book_info.author
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.author
     *
     * @param author the value for book_info.author
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.press
     *
     * @return the value of book_info.press
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.press
     *
     * @param press the value for book_info.press
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.number
     *
     * @return the value of book_info.number
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.number
     *
     * @param number the value for book_info.number
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.price
     *
     * @return the value of book_info.price
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.price
     *
     * @param price the value for book_info.price
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.create_time
     *
     * @return the value of book_info.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.create_time
     *
     * @param createTime the value for book_info.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.update_time
     *
     * @return the value of book_info.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.update_time
     *
     * @param updateTime the value for book_info.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}