package com.goumen.xiwan.entity;

import java.util.Date;

public class CreditOrder {
    @Override
    public String toString() {
        return "CreditOrder{" +
                "id=" + id +
                ", orderId=" + orderId +
                ", bookId=" + bookId +
                ", customerId=" + customerId +
                ", orderState=" + orderState +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.order_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.customer_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.order_state
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Byte orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_order.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.id
     *
     * @return the value of credit_order.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.id
     *
     * @param id the value for credit_order.id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.order_id
     *
     * @return the value of credit_order.order_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.order_id
     *
     * @param orderId the value for credit_order.order_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.book_id
     *
     * @return the value of credit_order.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.book_id
     *
     * @param bookId the value for credit_order.book_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.customer_id
     *
     * @return the value of credit_order.customer_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.customer_id
     *
     * @param customerId the value for credit_order.customer_id
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.order_state
     *
     * @return the value of credit_order.order_state
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Byte getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.order_state
     *
     * @param orderState the value for credit_order.order_state
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setOrderState(Byte orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.create_time
     *
     * @return the value of credit_order.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.create_time
     *
     * @param createTime the value for credit_order.create_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_order.update_time
     *
     * @return the value of credit_order.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_order.update_time
     *
     * @param updateTime the value for credit_order.update_time
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}