package com.goumen.xiwan.dao;

import com.goumen.xiwan.entity.BookInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface BookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int insert(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int insertSelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    BookInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int updateByPrimaryKeySelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int updateByPrimaryKey(BookInfo record);

    BookInfo selectByBookId(int bookId);
}