package com.goumen.xiwan.dao;

import com.goumen.xiwan.entity.CreditOrder;
import org.springframework.stereotype.Repository;

@Repository
public interface CreditOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int insert(CreditOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int insertSelective(CreditOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    CreditOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int updateByPrimaryKeySelective(CreditOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_order
     *
     * @mbggenerated Tue Oct 16 11:06:34 CST 2018
     */
    int updateByPrimaryKey(CreditOrder record);

    CreditOrder selectByCustomerId(int customerId);
}